# Site settings
title: haviet corporation
email: nikenhn@gmail.com
description: "another bootstrap site."
baseurl: ""
bstr: "haviet/bootstrap"
imgs: "haviet/images"


# Build settings
markdown: kramdown
permalink: pretty
